
import { useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import axiosInstance from "../API/axiosInstance";
import UseUser from "../UserContext/UserContext";

export default function AddBlog() {
  const { CurrentUser: user } = UseUser();
  const navigate = useNavigate();

  const [title, setTitle] = useState("");
  const [body, setBody] = useState("");
  const [coverImage, setCoverImage] = useState(null);
  const [preview, setPreview] = useState(null);
  const [isDragging, setIsDragging] = useState(false);
  const [aiLoading, setAiLoading] = useState(false);
  const fileInputRef = useRef(null);

  const handleImageDrop = (e) => {
    e.preventDefault();
    setIsDragging(false);
    const file = e.dataTransfer.files[0];
    if (file && file.type.startsWith("image/")) {
      setCoverImage(file);
      setPreview(URL.createObjectURL(file));
    }
  };

  const handleImageSelect = (e) => {
    const file = e.target.files[0];
    if (file) {
      setCoverImage(file);
      setPreview(URL.createObjectURL(file));
    }
  };

  const handleSubmit = async () => {
    if (!title.trim() || !body.trim()) {
      toast.error("Title and body are required.");
      return;
    }
    try {
      const formData = new FormData();
      formData.append("title", title);
      formData.append("body", body);
      formData.append("userId", user._id);
      if (coverImage) formData.append("coverImage", coverImage);

      await axiosInstance.post("/blog/addNewBlog", formData, {
        headers: { "Content-Type": "multipart/form-data" },
      });
      toast.success("Blog published!");
      navigate("/");
    } catch (err) {
      toast.error("Failed to publish blog.");
    }
  };

  const handleGenerateAI = async () => {
    if (!title.trim()) {
      toast.error("Please enter a title first.");
      return;
    }
    setAiLoading(true);
    try {
      const res = await axiosInstance.post("/blog/generate", { title });
      setBody(res.data.body || "");
      toast.success("Blog generated by AI!");
    } catch (err) {
      toast.error("AI generation failed.");
    } finally {
      setAiLoading(false);
    }
  };

  return (
    <div
      style={{
        minHeight: "100vh",
        backgroundColor: "#f8fafc",
        padding: "48px 24px 80px",
        fontFamily: "'Segoe UI', sans-serif",
      }}
    >
      <div
        style={{
          maxWidth: "700px",
          margin: "0 auto",
          backgroundColor: "#ffffff",
          borderRadius: "16px",
          boxShadow: "0 4px 32px rgba(0,0,0,0.08)",
          padding: "32px 40px",
        }}
      >
        {/* Page Title */}
        <p
          style={{
            fontSize: "0.78rem",
            fontWeight: 700,
            letterSpacing: "2px",
            textTransform: "uppercase",
            color: "#4f46e5",
            marginBottom: "32px",
          }}
        >
          New Story
        </p>

        {/* Cover Image Drop Zone */}
        <div
          onClick={() => fileInputRef.current?.click()}
          onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
          onDragLeave={() => setIsDragging(false)}
          onDrop={handleImageDrop}
          style={{
            width: "100%",
            height: preview ? "180px" : "120px",
            borderRadius: "12px",
            border: isDragging
              ? "2.5px dashed #4f46e5"
              : "2.5px dashed #cbd5e1",
            backgroundColor: isDragging ? "#eef2ff" : "#f8fafc",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            cursor: "pointer",
            marginBottom: "40px",
            overflow: "hidden",
            transition: "all 0.2s ease",
            position: "relative",
          }}
        >
          {preview ? (
            <img
              src={preview}
              alt="Cover preview"
              style={{
                width: "100%",
                height: "100%",
                objectFit: "cover",
              }}
            />
          ) : (
            <div style={{ textAlign: "center" }}>
              <div
                style={{
                  fontSize: "2.5rem",
                  marginBottom: "10px",
                  color: "#94a3b8",
                }}
              >
                🖼️
              </div>
              <p
                style={{
                  color: isDragging ? "#4f46e5" : "#94a3b8",
                  fontSize: "0.9rem",
                  margin: 0,
                  fontWeight: 500,
                }}
              >
                {isDragging
                  ? "Drop image here"
                  : "Drag & drop cover image, or click to browse"}
              </p>
              <p style={{ color: "#cbd5e1", fontSize: "0.78rem", marginTop: "4px" }}>
                PNG, JPG, WEBP supported
              </p>
            </div>
          )}
        </div>
        <input
          ref={fileInputRef}
          type="file"
          accept="image/*"
          style={{ display: "none" }}
          onChange={handleImageSelect}
        />

        {/* Title Input */}
        <textarea
          value={title}
          onChange={(e) => {
            setTitle(e.target.value);
            e.target.style.height = "auto";
            e.target.style.height = e.target.scrollHeight + "px";
          }}
          placeholder="Enter blog title..."
          rows={1}
          style={{
            width: "100%",
            border: "none",
            outline: "none",
            resize: "none",
            fontFamily: "'Georgia', serif",
            fontSize: "clamp(1rem, 3vw, 1.5rem)",
            fontWeight: 700,
            color: "#0f172a",
            lineHeight: 1.2,
            backgroundColor: "transparent",
            marginBottom: "20px",
            overflow: "hidden",
            boxSizing: "border-box",
            padding: 0,
          }}
        />

        {/* Thin Divider */}
        <div
          style={{
            height: "1px",
            backgroundColor: "#e2e8f0",
            marginBottom: "15px",
          }}
        />

        {/* Body Textarea */}
        <textarea
          value={body}
          onChange={(e) => {
            setBody(e.target.value);
            e.target.style.height = "auto";
            e.target.style.height = e.target.scrollHeight + "px";
          }}
          placeholder="Tell your story..."
          rows={8}
          style={{
            width: "100%",
            border: "none",
            outline: "none",
            resize: "none",
            fontFamily: "'Georgia', serif",
            fontSize: "0.92rem",
            color: "#7d8fa9",
            lineHeight: 1.7,
            backgroundColor: "transparent",
            marginBottom: "48px",
            boxSizing: "border-box",
            padding: 0,
            minHeight: "220px",
          }}
        />

        {/* Action Buttons */}
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "space-between",
            flexWrap: "wrap",
            gap: "16px",
            paddingTop: "24px",
            borderTop: "1px solid #f1f5f9",
          }}
        >
          {/* Submit Button */}
          <button
            onClick={handleSubmit}
            style={{
              padding: "12px 36px",
              borderRadius: "10px",
              backgroundColor: "#4f46e5",
              color: "#fff",
              border: "none",
              fontSize: "0.95rem",
              fontWeight: 700,
              cursor: "pointer",
              fontFamily: "'Segoe UI', sans-serif",
              boxShadow: "0 4px 12px rgba(79,70,229,0.3)",
              transition: "all 0.2s ease",
            }}
            onMouseEnter={(e) => {
              e.target.style.backgroundColor = "#4338ca";
              e.target.style.transform = "translateY(-1px)";
            }}
            onMouseLeave={(e) => {
              e.target.style.backgroundColor = "#4f46e5";
              e.target.style.transform = "translateY(0)";
            }}
          >
            Publish Story
          </button>

          {/* AI Generate Button */}
          {aiLoading ? (
            <div
              style={{
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                gap: "10px",
                padding: "12px 32px",
                borderRadius: "10px",
                background: "linear-gradient(135deg, #6366f1, #8b5cf6)",
                color: "#fff",
                fontSize: "0.9rem",
                fontWeight: 600,
                minWidth: "220px",
              }}
            >
              <svg
                width="18"
                height="18"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                strokeWidth="2.5"
                style={{ animation: "spin 1s linear infinite" }}
              >
                <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" />
              </svg>
              Generating...
              <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>
            </div>
          ) : (
            <button
              onClick={handleGenerateAI}
              style={{
                padding: "12px 28px",
                borderRadius: "10px",
                background: "linear-gradient(135deg, #6366f1 0%, #8b5cf6 100%)",
                color: "#fff",
                border: "none",
                fontSize: "0.9rem",
                fontWeight: 600,
                cursor: "pointer",
                fontFamily: "'Segoe UI', sans-serif",
                display: "flex",
                alignItems: "center",
                gap: "8px",
                boxShadow: "0 4px 12px rgba(139,92,246,0.3)",
                transition: "all 0.2s ease",
              }}
              onMouseEnter={(e) => {
                e.currentTarget.style.transform = "translateY(-1px)";
                e.currentTarget.style.boxShadow = "0 6px 20px rgba(139,92,246,0.4)";
              }}
              onMouseLeave={(e) => {
                e.currentTarget.style.transform = "translateY(0)";
                e.currentTarget.style.boxShadow = "0 4px 12px rgba(139,92,246,0.3)";
              }}
            >
              <span style={{ fontSize: "1.1rem" }}>✨</span>
              Generate Blog from AI
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
